# Generated by Django 6.0.3

from django.db import migrations, models
from django.utils import timezone


def populate_category_slugs(apps, schema_editor):
    Category = apps.get_model("web", "Category")
    for cat in Category.objects.all():
        base = cat.name.lower().replace(" ", "-")
        slug = "".join(c if c.isalnum() or c == "-" else "" for c in base)
        slug = slug.strip("-") or "cat-%s" % cat.pk
        # ensure uniqueness
        original = slug
        n = 0
        while Category.objects.filter(slug=slug).exclude(pk=cat.pk).exists():
            n += 1
            slug = "%s-%d" % (original, n)
        cat.slug = slug
        cat.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, db_index=False, null=True, unique=False),
        ),
        migrations.RunPython(populate_category_slugs, noop),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, db_index=True),
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RunPython(
            lambda apps, se: apps.get_model("web", "Post").objects.filter(created_at__isnull=True).update(created_at=timezone.now()),
            noop,
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
