# Generated by Django 6.0.3 on 2026-03-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_category_options_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
